In [1]:
import numpy as np


In [ ]:
Answer 1:

In [2]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

In [3]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


list_ is a Python list, while array_list is a NumPy array

So, list_ is of type list, while array_list is of type numpy.ndarray

In [ ]:
Answer 2:

In [4]:
# Print data type of each element in list_
for element in list_:
    print(type(element))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


As you can see, the elements in list_ are all of type str, while the elements in array_list are of
 type numpy.str_

In [ ]:
Answer 3:

Yes, there will be a difference in the data type of the elements present in list_ and array_list after the following change:

In [6]:
array_list = np.array(list_, dtype=int)


Here, we are specifying the dtype parameter as int which means that the elements in the resulting NumPy array will be of integer type.

To print the data type of each and every element present in both variables list_ and array_list, you can use a loop to iterate through each element and apply the type() function. 

Here's an example code:

In [7]:
# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Answer 4:

In [8]:


num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [9]:
# Print shape of num_array
print("Shape of num_array:", num_array.shape)

# Print size of num_array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Answer 5:

To create a NumPy array of 3x3 matrix containing zeros only, you can use the np.zeros() function.
Here's an example code:

In [10]:
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Answer 6:

In [11]:

identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
