In [ ]:
##Sort, Search & Counting Functions.

In [1]:
import numpy as np

In [2]:
arr = np.array([4,2,8,5,3,9,12,56])

In [3]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [4]:
# sort the array in ascending order and then returns the array.

np.sort(arr)

# we can also sort the array in descending order.

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [5]:
# we are trying to search for 6 in sorted array, 
# It finds indices where element should be inserted to maintain order.

np.searchsorted(arr,6)
# It means we can insert element "6" at 5th index so that order of array is maintained.

5

In [6]:


arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [7]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [8]:
# counting function.

np.count_nonzero(arr1)

# counts the number of Non-zero numbers, and then return the count of it.

6

In [9]:
# where() -> it gives the index what is the data that satisfies the condition, based on what we search for.

np.where(arr1 > 0 )

# Here at the indices 1, 2, 3, 4, 5, 9 we have indices where number > 0.

(array([1, 2, 3, 4, 5, 9]),)

In [10]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [ ]:
#Numpy - Byte Swapping.

In [11]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [12]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [13]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [14]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
#Numpy - Copies &Views.

In [15]:
a = np.copy(arr1)

In [16]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [17]:
b = arr1.view()

In [18]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [19]:
b = arr1

In [20]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [21]:
b[0] = 234

In [22]:
b

# Here "b" is a view and it follows shallow copy, but not deep copy.

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [23]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)