In [4]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.5))

# range() will always consider integers.

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
# In Numpy we have function called arange, similar to range but it also accepts float numbers(decimal)

np.arange(0.4,10.5)

array([ 0.4,  1.4,  2.4,  3.4,  4.4,  5.4,  6.4,  7.4,  8.4,  9.4, 10.4])

In [8]:
np.arange(0.4,10.5,0.2)

# Here we have given step size, the difference between any 2 successive elements.

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [9]:
list(np.arange(0.4,10.5,0.2))

# converting the above array into a list.

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [10]:
# To generate data between 2 points with equal differences between them i.e 1 and 5 here and how many number of
# elements do we require here(20).

np.linspace(1,5, 20)

# It divides the scale between 1 and 5 into 20 divisions with equal difference these 20 elements.

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
np.logspace(1,5, 10)

# Here by default base is 10, 

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [12]:
# generating the numbers with base2
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [13]:
np.zeros(5)

# creates 1 dimensional array with mentioned number of zeroes.

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

# creates a 2 dimensional array, with all zeroes where 1st mentioned index is number o rows and the 2nd mentioned
# index is the number of columns.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4,2))

# here it means we have (4,2) arrays which are 2 dimensional arrays and 3rd dimension is how many number of such
# 2 dimensional arrays are present.

# (i,j,k) -> it means we have "i" number of (j,k) number of 2 dimensional arrays. 

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((3,4,2,3))


# we will get 3 number of (4,2,3) matrices.

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
# generates an array of 1's 

np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
arr = np.ones((3,4))

In [20]:
arr + 5

# For each element in array, 

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [23]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [24]:
# Identity matrix : only diagonal elements are 1, and non-diagonal elements will be zero.
# Identity matrix : is always a square matrix(No.of rows = No.of columns)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr1 = np.eye(5)

In [25]:
# converting the array into a dataframe:

import pandas as pd

In [28]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [2]:
# For generating random data: generates data randomly.

np.random.rand(3,2)

array([[0.30228318, 0.2079964 ],
       [0.38057657, 0.94930198],
       [0.31535568, 0.01048755]])

In [4]:

np.random.randn(3,2)

array([[ 1.3278357 , -0.72859867],
       [ 0.54661492,  1.223045  ],
       [-0.63259471, -0.56819247]])

In [ ]:
# Difference between rand() and randn()

rand() - It generates random numbers, where mean and std deviation can be anything
randn() - standard normal distribution( mean = 0, std deviation = 1) 

In [5]:
# generates random data between a given range of the specified shape

np.random.randint(1,5, (3,4))
# We need a matrix of size 3*4 where all the elements should be between 1 and 5.

# such functions are very effective for data manipulation

array([[3, 4, 3, 4],
       [2, 1, 1, 1],
       [1, 2, 1, 3]])

In [6]:
arr2 = np.random.randint(1,5, (3,4))

In [7]:
arr2.size

12

In [8]:
arr2.shape

(3, 4)

In [10]:
# Assume we want to change the shape, then we can use reshape()
# we should make sure that the total number of elements in new shape must be same as that of previous shape.

arr2.reshape(6,2)

array([[1, 3],
       [4, 1],
       [1, 3],
       [4, 3],
       [2, 4],
       [3, 4]])

In [11]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [12]:
arr2.reshape(2,6)

array([[1, 3, 4, 1, 1, 3],
       [4, 3, 2, 4, 3, 4]])

In [13]:
arr2.reshape(4,3)

array([[1, 3, 4],
       [1, 1, 3],
       [4, 3, 2],
       [4, 3, 4]])

In [14]:
arr2.reshape(4,-1)

# for 2nd number in shape we can give any number. It's completely fine.

array([[1, 3, 4],
       [1, 1, 3],
       [4, 3, 2],
       [4, 3, 4]])

In [15]:
arr2.reshape(4,-33)

array([[1, 3, 4],
       [1, 1, 3],
       [4, 3, 2],
       [4, 3, 4]])

In [16]:
arr2.reshape(2,2,3)

array([[[1, 3, 4],
        [1, 1, 3]],

       [[4, 3, 2],
        [4, 3, 4]]])

In [21]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[1]]],


         [[[3]]],


         [[[4]]]],



        [[[[1]]],


         [[[1]]],


         [[[3]]]]],




       [[[[[4]]],


         [[[3]]],


         [[[2]]]],



        [[[[4]]],


         [[[3]]],


         [[[4]]]]]])

In [18]:
arr3 = np.random.randint(1,10, (5,6))

# generate a dataset, such that all elements are in range(1,10) and we need an array of size (5,6).

In [19]:
arr3

array([[7, 9, 8, 1, 1, 6],
       [5, 4, 9, 5, 7, 4],
       [4, 1, 7, 6, 3, 9],
       [1, 8, 3, 8, 5, 8],
       [3, 8, 1, 3, 6, 4]])

In [20]:
# Let's try to filter all the data where elements are > 7.

arr3 > 7 # this returns a boolean array.

array([[False,  True,  True, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False, False, False, False]])

In [23]:
arr3[arr3 >8]

array([9, 9, 9])

In [25]:
# Extracting part(subset) of 2 D array
# Eg: First 2 elements in 1st row.


arr3[0,[0,1]]

# The 1st number , tells what is the row number and the 2nd number tells

array([7, 9])

In [26]:
arr3[2:4 , [2,3]]

# From 2nd and 3rd row, (start to end-1) it gets elements in range(2,3)
# This is similar to List Slicing and Indexing.

array([[7, 6],
       [3, 8]])

In [27]:
np.random.randint(1,3, (3,3))

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [5]:
arr4 = np.random.randint(1,3, (3,3))

In [29]:
arr5 = np.random.randint(1,3, (3,3))

In [30]:
arr4 + arr5

# Here it performs index wise addition operation.

array([[3, 3, 3],
       [4, 3, 4],
       [2, 3, 4]])

In [31]:
arr4 - arr5

array([[ 1, -1,  1],
       [ 0,  1,  0],
       [ 0, -1,  0]])

In [32]:
arr4 * arr5

# Here it performs index wise multiplication operation.


array([[2, 2, 2],
       [4, 2, 4],
       [1, 2, 4]])

In [ ]:
# How we will be able to do Matrix multiplication:
# To accomplish matrix multiplication, the no.of columns in 1st matrix have to be equal to no.of rows in 1st matrix

# if m1 is 3*4 size, and m2 is 4*5 size then m1*m2 is of size "3*5".
# If m1 is of size p*q , and m2 is of size l*m then q=l, then only matrix multiplication is possible.

matrix multiplication is done by taking row wise(a row) and column wise(a column)

Eg: To obtain 1,2 element in resultant matrix, then 1st row in mat1 and 2nd column in 2nd matrix, and then do
  element wise multiplication followed by addition of all multiplied elements to get the resultant element at 
  that index.

In [33]:
arr4@arr5

# Matrix multiplication.

array([[ 6,  9,  8],
       [ 8, 10, 10],
       [ 5,  7,  7]])

In [34]:
arr4/arr5

array([[2. , 0.5, 2. ],
       [1. , 2. , 1. ],
       [1. , 0.5, 1. ]])

In [6]:
arr4/0

# here it gives infinity, but in python it gives divide by zero(0) exception.

/tmp/ipykernel_1773/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [8]:
# Numpy - Broadcasting:

arr6 = np.zeros((3,4))

In [9]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr6 + 5

# Here we are trying to broadcast the same to each and every element in array.

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [11]:
a = np.array([1,2,3,4])

In [12]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [13]:
b = np.array([[3,4,5]])

In [14]:
arr7 = arr6 + b.T

In [15]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [16]:
b.T

array([[3],
       [4],
       [5]])

In [17]:
# Finding square root of every element in array.

np.sqrt(arr7)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [18]:
# Finding log with respect to base 10.

np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [20]:
# Finding exponent with respect to "e"

np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [21]:
np.min(arr7)

3.0

In [22]:
np.max(arr7)

5.0