Previously there is a package called 'matlab', there are lot of mathematical functions which are available in 
that. In python there are no such libraries for mathematical operations that are available.


So a mathematical package was created for mathematical operations called 'Numpy'. Using Numpy we can perform any
matrix and array based calculation.

Numpy means "Numerical Python".Any operations related to arrays and matrix can be performed using Numpy. 
Numpy is created for array and matrix calculations.

In [2]:
# import numpy
# as is used for aliasing(rename), so that instead of using numpy we can just use np.
import numpy as np

In [3]:
l = [1,2,3,4,5,6]

In [4]:
# converting a list to array

np.array(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
arr = np.array(l)

In [6]:
# checking the type of array

type(arr)


numpy.ndarray

In [ ]:
# It means it is a numpy n-dimensional array.

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [8]:
arr1 = np.array([[1,2,3] , [2,3,4]])

# creating a 2 dimensional numpy array.

In [9]:
type(arr1)

numpy.ndarray

In [10]:
# finding how many number of dimensions an array have:

arr1.ndim

# we can assume that 2 dimensional array starts with indces 0 and 0 for both.

2

In [11]:
arr.ndim

1

In [12]:
# understanding matrix() in numpy.

np.matrix(l)

# By default, matrix has minimum of 2 dimensions. Array can have 1 dimension.
# Matrix will always have atleast 2 dimensions at any point of time.

matrix([[1, 2, 3, 4, 5, 6]])

In [13]:
mat = np.matrix(l)

In [14]:
np.asanyarray(l)

# converts list into array.

array([1, 2, 3, 4, 5, 6])

In [15]:
np.asanyarray(mat)

# asanarray() converts anything into array if it is not an array. 
# matrx is a sub class of array. So the result of above operation is matrix. Matrix is also a type of array.

matrix([[1, 2, 3, 4, 5, 6]])

In [16]:
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
a = arr

In [18]:
a

array([1, 2, 3, 4, 5, 6])

In [19]:
arr

array([1, 2, 3, 4, 5, 6])

In [20]:
# making changes in arr.
arr[0] = 100

In [21]:
a

array([100,   2,   3,   4,   5,   6])

In [22]:
arr

array([100,   2,   3,   4,   5,   6])

In [ ]:
# here the copy operation, that is performed is shallow copy but not deep copy, both 'a' and 'arr' are references 
# to the same array.

# we are not creating new copy of 'arr' andthennassigning it to 'a'.
# 'a' refers to same memory location as that of 'arr'. Both are references to the same location in memory.

# shallow copy doesb't copy the data, instead it just creates a new reference to the existing copy.

In [23]:
b = np.copy(arr)

In [24]:
b

array([100,   2,   3,   4,   5,   6])

In [25]:
b[0] = 50

In [26]:
arr

array([100,   2,   3,   4,   5,   6])

In [27]:
b

array([50,  2,  3,  4,  5,  6])

In [ ]:
# So here we can see that upon using copy() another copy of same data is created in memory and new copy is being 
# referred by 'b'.
# So any changes that are made on'b' will be visible only to 'b' and they don't get reflected on 'arr'
# seperate memory will be cretaed and then it assigns the reference to newly created memory.


# This is the main difference between shallow copy and deep copy.
# This is how we can create reference variable/reference pointer at any time.

# In Numpy, we can find many dfferent functions through which we can create different types of array.

In [28]:
# here (3,3) is the shape of the array

np.fromfunction(lambda i, j : i == j, (3,3) )


# Here when both row number, and column number are equal then we have 1, else we have 0.
# So for i, j = (00, 11, 22) we have met the above condition so for them we have 1.

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i, j : i * j, (3,3) )

# Here the indices will be multiplied and then the result will be returned.
# from function is one kind of function in which we can generate a dataset.

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7feb8c131460>

In [31]:
iterable = (i*i for i in range(5))

In [35]:
# passing the above iterable

np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
# it iterates the below iterable and finds elements based on whitespace(' ') as seperator.

np.fromstring('23 45', sep=' ')

# In Numpy, majority of the methods that are present will return an array as output.

array([23., 45.])

In [39]:
np.fromstring('23,45,56', sep=',')

array([23., 45., 56.])

In [37]:
np.fromstring('23 sdf   fd dc cde fg 45', sep=' ')

/tmp/ipykernel_299/2196023286.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('23 sdf   fd dc cde fg 45', sep=' ')


array([23.])

In [40]:
arr

array([100,   2,   3,   4,   5,   6])

In [41]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
arr1.ndim

2

In [43]:
arr.size

# returns the number of elements in the array.

6

In [44]:
arr1.size

6

In [45]:
arr.shape

(6,)

In [46]:
arr1.shape

# It means arr1 has 2 rows and 3 columns.

(2, 3)

In [47]:
arr.dtype

# data type of particular array.

dtype('int64')

In [ ]:
arr1.dtype