In [1]:
import numpy as np

In [ ]:
#Numpy - Array Manipulation.

In [2]:
# generates random integers in range of (1,10) as 2D Array, whose size is 4*4

arr = np.random.randint(1,10 , (4,4))

In [3]:
arr

array([[1, 3, 2, 7],
       [9, 8, 9, 5],
       [4, 4, 3, 9],
       [3, 2, 4, 2]])

In [4]:
# changing the shape of array, such that total no.of elements in new shape must be equal to no.of elements in 
# actual array.

arr.reshape(8,2)

array([[1, 3],
       [2, 7],
       [9, 8],
       [9, 5],
       [4, 4],
       [3, 9],
       [3, 2],
       [4, 2]])

In [5]:
arr

array([[1, 3, 2, 7],
       [9, 8, 9, 5],
       [4, 4, 3, 9],
       [3, 2, 4, 2]])

In [6]:
# Transpose : rows and columns are interchanged.

arr.T

# arr.T is a property used in Python to get the transpose of a NumPy array arr

# The property returns a view of the original array with its axes transposed, i.e., the rows become columns and
# the columns become rows.

array([[1, 9, 4, 3],
       [3, 8, 4, 2],
       [2, 9, 3, 4],
       [7, 5, 9, 2]])

In [7]:
# arr.flatten() is a method used in Python to convert a multi-dimensional array arr into a one-dimensional array. 

arr.flatten()

# The method returns a copy of the original array with all the elements flattened or unraveled into a single
# dimension.

array([1, 3, 2, 7, 9, 8, 9, 5, 4, 4, 3, 9, 3, 2, 4, 2])

In [8]:
arr

array([[1, 3, 2, 7],
       [9, 8, 9, 5],
       [4, 4, 3, 9],
       [3, 2, 4, 2]])

In [9]:
np.expand_dims(arr,axis=1)

# np.expand_dims(arr, axis=1) is a NumPy function that is used to add a new axis to a NumPy array arr.
# The new axis is added at the specified position (axis=1 in this case), which creates a new dimension with size 1.

array([[[1, 3, 2, 7]],

       [[9, 8, 9, 5]],

       [[4, 4, 3, 9]],

       [[3, 2, 4, 2]]])

In [10]:
np.expand_dims(arr,axis=0)

#  np.expand_dims(arr, axis=0) is a NumPy function that is used to add a new axis to a NumPy array arr. The new
# axis is added at the specified position (axis=0 in this case), which creates a new dimension with size 1.

array([[[1, 3, 2, 7],
        [9, 8, 9, 5],
        [4, 4, 3, 9],
        [3, 2, 4, 2]]])

In [11]:
data = np.array([[1] , [2] , [3]])

In [12]:
np.squeeze(data)

# np.squeeze(data) is a NumPy function that is used to remove single-dimensional entries (i.e., dimensions with
# size 1) from the shape of a NumPy array data. If an array has multiple dimensions with size 1, np.squeeze() will 
# remove all of them


# np.squeeze(data) returns a new array, rather than modifying the original array in place. You can use this 
# function to reduce the dimensions of an array to simplify the shape for downstream processing, or to remove
# batch or channel dimensions that are no longer needed.

array([1, 2, 3])

In [13]:
np.repeat(data,4)

# np.repeat(data, 4) is a NumPy function that is used to repeat each element in a NumPy array data a specified 
# number of times (4 in this case). The result is a new NumPy array with a larger size than the original array.


# np.repeat(data, 4) returns a new array, rather than modifying the original array in place. You can use this 
# function to repeat an array to match the size of another array or to prepare an array for broadcasting operations.

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [14]:
# rotates all the elements of an array by specified number of times. Here 2 in this case.

np.roll(data,2)

# np.roll(data, shift) is a NumPy function that is used to shift the elements of a NumPy array data along a
# specified axis by a certain number of positions

array([[2],
       [3],
       [1]])

In [15]:
np.roll(data,3)

# np.roll(data, shift) returns a new array, rather than modifying the original array in place. You can use this
# function to create a circular shift in an array or to shift the elements of an array to align with another array.

array([[1],
       [2],
       [3]])

In [16]:
np.diag(np.array([1,2,3,4]))

# creates a diagonal matrix with the elements of array as the diagonal elements.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

np.diag() is a NumPy function that is used to create a diagonal array or extract the diagonal elements of an array.

When given a one-dimensional array as input, np.diag() returns a new two-dimensional array with the input array on the diagonal and zeros everywhere else.

When given a two-dimensional array as input, np.diag() returns a one-dimensional array containing the diagonal elements of the input array.

In [ ]:
#Numpy - Binary Operators.

In [17]:
arr6 = np.random.randint(1,10 , (3,4))
arr7 = np.random.randint(1,10 , (3,4))

In [18]:
arr6

array([[6, 3, 7, 1],
       [2, 5, 4, 5],
       [6, 3, 7, 2]])

In [19]:
arr7

array([[9, 8, 4, 9],
       [8, 4, 3, 6],
       [4, 1, 9, 4]])

In [20]:
arr6 + arr7

array([[15, 11, 11, 10],
       [10,  9,  7, 11],
       [10,  4, 16,  6]])

In [21]:
arr6 - arr7

array([[-3, -5,  3, -8],
       [-6,  1,  1, -1],
       [ 2,  2, -2, -2]])

In [22]:
arr6 * arr7

array([[54, 24, 28,  9],
       [16, 20, 12, 30],
       [24,  3, 63,  8]])

In [23]:
arr6 / arr7

array([[0.66666667, 0.375     , 1.75      , 0.11111111],
       [0.25      , 1.25      , 1.33333333, 0.83333333],
       [1.5       , 3.        , 0.77777778, 0.5       ]])

In [24]:
arr6 ** arr7

# index wise exponential operation will be performed.

array([[10077696,     6561,     2401,        1],
       [     256,      625,       64,    15625],
       [    1296,        3, 40353607,       16]])

In [25]:
~arr6

array([[-7, -4, -8, -2],
       [-3, -6, -5, -6],
       [-7, -4, -8, -3]])

In [26]:
arr6

array([[6, 3, 7, 1],
       [2, 5, 4, 5],
       [6, 3, 7, 2]])

~ is the Bitwise NOT operator in Python. When used with a NumPy array, it performs a bitwise NOT operation on each element of the array.

It returns a new array with the result of the operation.

In [27]:
arr6 > arr7

array([[False, False,  True, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])

In [ ]:
#Numpy - String Functions.

In [30]:
arr = np.array(["srinath" , "reddy"])

In [31]:
arr

array(['srinath', 'reddy'], dtype='<U7')

In [32]:
np.char.upper(arr)

array(['SRINATH', 'REDDY'], dtype='<U7')

In [33]:
np.char.capitalize(arr)

array(['Srinath', 'Reddy'], dtype='<U7')

In [34]:
np.char.title(arr)

array(['Srinath', 'Reddy'], dtype='<U7')

In [ ]:
#Numpy - Mathematical Functions.

In [35]:
arr6

array([[6, 3, 7, 1],
       [2, 5, 4, 5],
       [6, 3, 7, 2]])

In [36]:
np.sin(arr6)

# Trigonometric sin theta

array([[-0.2794155 ,  0.14112001,  0.6569866 ,  0.84147098],
       [ 0.90929743, -0.95892427, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.14112001,  0.6569866 ,  0.90929743]])

In [37]:
np.cos(arr6)

array([[ 0.96017029, -0.9899925 ,  0.75390225,  0.54030231],
       [-0.41614684,  0.28366219, -0.65364362,  0.28366219],
       [ 0.96017029, -0.9899925 ,  0.75390225, -0.41614684]])

In [38]:
np.tan(arr6)

array([[-0.29100619, -0.14254654,  0.87144798,  1.55740772],
       [-2.18503986, -3.38051501,  1.15782128, -3.38051501],
       [-0.29100619, -0.14254654,  0.87144798, -2.18503986]])

In [39]:
np.log10(arr6)

array([[0.77815125, 0.47712125, 0.84509804, 0.        ],
       [0.30103   , 0.69897   , 0.60205999, 0.69897   ],
       [0.77815125, 0.47712125, 0.84509804, 0.30103   ]])

In [40]:
# Taking exponent(each element) in the array i.e e^

np.exp(arr6)

array([[ 403.42879349,   20.08553692, 1096.63315843,    2.71828183],
       [   7.3890561 ,  148.4131591 ,   54.59815003,  148.4131591 ],
       [ 403.42879349,   20.08553692, 1096.63315843,    7.3890561 ]])

In [42]:
np.power(arr6,2)

array([[36,  9, 49,  1],
       [ 4, 25, 16, 25],
       [36,  9, 49,  4]])

In [ ]:
#Numpy - Statistical Functions.

In [43]:
np.mean(arr6)

4.25

In [44]:
np.median(arr6)

4.5

In [45]:
np.mode(arr6)

AttributeError: module 'numpy' has no attribute 'mode'

In [46]:
np.std(arr6)

# Deviation from mean is called standard deviation.

1.963203164898291

In [47]:
np.var(arr6)

3.8541666666666665

In [48]:
np.min(arr6)

1

In [49]:
np.max(arr6)

7

In [ ]:
#Numpy - Arithmetic Operations.

In [50]:
np.subtract(arr6,arr7)

array([[-3, -5,  3, -8],
       [-6,  1,  1, -1],
       [ 2,  2, -2, -2]])

In [51]:
np.multiply(arr6,arr7)

array([[54, 24, 28,  9],
       [16, 20, 12, 30],
       [24,  3, 63,  8]])

In [52]:
np.mod(arr6,arr7)

array([[6, 3, 3, 1],
       [2, 1, 1, 5],
       [2, 0, 7, 2]])

In [53]:
np.power(arr6,arr7)

array([[10077696,     6561,     2401,        1],
       [     256,      625,       64,    15625],
       [    1296,        3, 40353607,       16]])

In [54]:
np.sqrt(arr6)

array([[2.44948974, 1.73205081, 2.64575131, 1.        ],
       [1.41421356, 2.23606798, 2.        , 2.23606798],
       [2.44948974, 1.73205081, 2.64575131, 1.41421356]])